name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [ 1.18,1.19,1.20.x ]
    name: build & test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: cache-go-${{ runner.os }}-${{ matrix.go-version }}-${{ github.run_number }}
          restore-keys: |
            cache-go-${{ runner.os }}-${{ matrix.go-version }}-

      - name: Test
        run: make test-v

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .testCoverage.txt