name: Lint

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    strategy:
      matrix:
        go: [ 1.18,1.19,1.20.x ]
        os: [ ubuntu-latest ]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.workdir }}
          skip-pkg-cache: true